trigger: 
-  main

pool: Todo_Microservice_Pool

stages:
- stage: Initial_Stage
  displayName: Pre Check
  jobs:
  - job: Terraform_Install
    displayName: Terraform Init
    steps: 
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
        backendServiceArm: 'TodoApp_Service'
        backendAzureRmResourceGroupName: 'Brijendra_RG'
        backendAzureRmStorageAccountName: 'brijendrastoragelab'
        backendAzureRmContainerName: 'brijendracontainerlab'
        backendAzureRmKey: 'aksdev.terraformtfstate'